/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import classes.Som;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author MariaEduardaMiuke - 2 DS A
 */
public class Urna extends javax.swing.JFrame {
    
    public String nmr = "", 
    numCand = "";

    /**
     * Creates new form Urna
     */
    public Urna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        nmr2 = new javax.swing.JButton();
        nmr3 = new javax.swing.JButton();
        nmr1 = new javax.swing.JButton();
        nmr4 = new javax.swing.JButton();
        nmr5 = new javax.swing.JButton();
        nmr6 = new javax.swing.JButton();
        nmr8 = new javax.swing.JButton();
        nmr7 = new javax.swing.JButton();
        nmr0 = new javax.swing.JButton();
        nmr9 = new javax.swing.JButton();
        candidato = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        cargo = new javax.swing.JLabel();
        espac1 = new javax.swing.JTextField();
        btnbranco = new javax.swing.JButton();
        btncorrige = new javax.swing.JButton();
        btnconfirma = new javax.swing.JButton();
        espac3 = new javax.swing.JTextField();
        espac2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        nmr2.setText("2");
        nmr2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nmr2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nmr2MouseClicked(evt);
            }
        });
        nmr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmr2ActionPerformed(evt);
            }
        });

        nmr3.setText("3");
        nmr3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nmr3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nmr3MouseClicked(evt);
            }
        });
        nmr3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmr3ActionPerformed(evt);
            }
        });

        nmr1.setText("1");
        nmr1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nmr1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nmr1MouseClicked(evt);
            }
        });
        nmr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmr1ActionPerformed(evt);
            }
        });

        nmr4.setText("4");
        nmr4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nmr4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nmr4MouseClicked(evt);
            }
        });
        nmr4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmr4ActionPerformed(evt);
            }
        });

        nmr5.setText("5");
        nmr5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nmr5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nmr5MouseClicked(evt);
            }
        });
        nmr5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmr5ActionPerformed(evt);
            }
        });

        nmr6.setText("6");
        nmr6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nmr6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nmr6MouseClicked(evt);
            }
        });
        nmr6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmr6ActionPerformed(evt);
            }
        });

        nmr8.setText("8");
        nmr8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nmr8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nmr8MouseClicked(evt);
            }
        });
        nmr8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmr8ActionPerformed(evt);
            }
        });

        nmr7.setText("7");
        nmr7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nmr7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nmr7MouseClicked(evt);
            }
        });
        nmr7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmr7ActionPerformed(evt);
            }
        });

        nmr0.setText("0");
        nmr0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nmr0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nmr0MouseClicked(evt);
            }
        });
        nmr0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmr0ActionPerformed(evt);
            }
        });

        nmr9.setText("9");
        nmr9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nmr9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nmr9MouseClicked(evt);
            }
        });
        nmr9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmr9ActionPerformed(evt);
            }
        });

        candidato.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nome.setText("Nome do Candidato ");
        nome.setAutoscrolls(true);
        nome.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cargo.setText("cargo");
        cargo.setAutoscrolls(true);
        cargo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        espac1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        espac1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                espac1MouseClicked(evt);
            }
        });
        espac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espac1ActionPerformed(evt);
            }
        });

        btnbranco.setBackground(new java.awt.Color(255, 255, 255));
        btnbranco.setText("BRANCO");
        btnbranco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnbranco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbrancoMouseClicked(evt);
            }
        });
        btnbranco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbrancoActionPerformed(evt);
            }
        });

        btncorrige.setBackground(new java.awt.Color(153, 0, 0));
        btncorrige.setText("CORRIGE");
        btncorrige.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btncorrige.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncorrigeMouseClicked(evt);
            }
        });
        btncorrige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncorrigeActionPerformed(evt);
            }
        });

        btnconfirma.setBackground(new java.awt.Color(0, 204, 0));
        btnconfirma.setText("CONFIRMA");
        btnconfirma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnconfirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnconfirmaMouseClicked(evt);
            }
        });
        btnconfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmaActionPerformed(evt);
            }
        });

        espac3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        espac3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espac3ActionPerformed(evt);
            }
        });

        espac2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        espac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espac2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Potter - 110");
        jPanel1.add(jLabel1);

        jLabel2.setText("Hermione - 111");
        jPanel1.add(jLabel2);

        jLabel3.setText("Rony - 112");
        jPanel1.add(jLabel3);

        jLabel4.setText("Draco - 113");
        jPanel1.add(jLabel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(candidato, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(espac1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(espac2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(espac3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nmr1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nmr4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nmr7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nmr2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nmr5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nmr8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nmr0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nmr9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nmr3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nmr6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btnconfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnbranco, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(nome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cargo)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(candidato, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(espac1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(espac2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(espac3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nmr1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(nmr4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(nmr7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nmr2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(nmr5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(nmr8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(nmr0, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nmr3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(nmr6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(nmr9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnconfirma)
                            .addComponent(btnbranco)
                            .addComponent(btncorrige))))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void nmr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmr2ActionPerformed
    String caminho = "E:\\UrnaEletronica\\Tecla.wav";
    Som a = new Som();
    a.Som (caminho);  
    }//GEN-LAST:event_nmr2ActionPerformed

    private void nmr3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmr3ActionPerformed
    String caminho = "E:\\UrnaEletronica\\Tecla.wav";
    Som a = new Som();
    a.Som (caminho);  
    }//GEN-LAST:event_nmr3ActionPerformed

    private void nmr8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmr8ActionPerformed
    String caminho = "E:\\UrnaEletronica\\Tecla.wav";
    Som a = new Som();
    a.Som (caminho);  
    }//GEN-LAST:event_nmr8ActionPerformed

    private void nmr1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nmr1MouseClicked
    nmr = "1";    
    MostrarNum();
    }//GEN-LAST:event_nmr1MouseClicked

    private void nmr2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nmr2MouseClicked
    nmr = "2";    
    MostrarNum();
    }//GEN-LAST:event_nmr2MouseClicked

    private void nmr3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nmr3MouseClicked
    nmr = "3";    
    MostrarNum();
    }//GEN-LAST:event_nmr3MouseClicked

    private void nmr4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nmr4MouseClicked
    nmr = "4";    
    MostrarNum();
    }//GEN-LAST:event_nmr4MouseClicked

    private void nmr5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nmr5MouseClicked
    nmr = "5";    
    MostrarNum();
    }//GEN-LAST:event_nmr5MouseClicked

    private void nmr6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nmr6MouseClicked
    nmr = "6";    
    MostrarNum();
    }//GEN-LAST:event_nmr6MouseClicked

    private void nmr7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nmr7MouseClicked
    nmr = "7";    
    MostrarNum();
    }//GEN-LAST:event_nmr7MouseClicked

    private void nmr8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nmr8MouseClicked
    nmr = "8";    
    MostrarNum();
    }//GEN-LAST:event_nmr8MouseClicked

    private void nmr9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nmr9MouseClicked
    nmr = "9";    
    MostrarNum();
    }//GEN-LAST:event_nmr9MouseClicked

    private void nmr0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nmr0MouseClicked
    nmr = "0";    
    MostrarNum();
    }//GEN-LAST:event_nmr0MouseClicked

    private void espac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espac1ActionPerformed

    }//GEN-LAST:event_espac1ActionPerformed

    private void nmr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmr1ActionPerformed
    String caminho = "E:\\UrnaEletronica\\Tecla.wav";
    Som a = new Som();
    a.Som (caminho);               
    }//GEN-LAST:event_nmr1ActionPerformed

    private void nmr4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmr4ActionPerformed
    String caminho = "E:\\UrnaEletronica\\Tecla.wav";
    Som a = new Som();
    a.Som (caminho);
    }//GEN-LAST:event_nmr4ActionPerformed

    private void nmr5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmr5ActionPerformed
    String caminho = "E:\\UrnaEletronica\\Tecla.wav";
    Som a = new Som();
    a.Som (caminho);
    }//GEN-LAST:event_nmr5ActionPerformed

    private void nmr6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmr6ActionPerformed
    String caminho = "E:\\UrnaEletronica\\Tecla.wav";
    Som a = new Som();
    a.Som (caminho);
    }//GEN-LAST:event_nmr6ActionPerformed

    private void nmr7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmr7ActionPerformed
    String caminho = "E:\\UrnaEletronica\\Tecla.wav";
    Som a = new Som();
    a.Som (caminho);
    }//GEN-LAST:event_nmr7ActionPerformed

    private void nmr9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmr9ActionPerformed
    String caminho = "E:\\UrnaEletronica\\Tecla.wav";
    Som a = new Som();
    a.Som (caminho);
    }//GEN-LAST:event_nmr9ActionPerformed

    private void nmr0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmr0ActionPerformed
    String caminho = "E:\\UrnaEletronica\\Tecla.wav";
    Som a = new Som();
    a.Som (caminho);
    }//GEN-LAST:event_nmr0ActionPerformed

    private void btncorrigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncorrigeActionPerformed
    String caminho = "E:\\UrnaEletronica\\Tecla.wav";
    Som a = new Som();
    a.Som (caminho);      
    }//GEN-LAST:event_btncorrigeActionPerformed

    private void btnbrancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbrancoActionPerformed
    String caminho = "E:\\UrnaEletronica\\urna.wav";
    Som a = new Som();
    a.Som (caminho);    
    }//GEN-LAST:event_btnbrancoActionPerformed

    private void btnconfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmaActionPerformed
    String caminho = "E:\\UrnaEletronica\\urna.wav";
    Som a = new Som();
    a.Som (caminho);    
    }//GEN-LAST:event_btnconfirmaActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void espac3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espac3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espac3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void espac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espac2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_espac2ActionPerformed

    private void espac1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_espac1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_espac1MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btnconfirmaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfirmaMouseClicked
    {      
    int confirma = JOptionPane.showConfirmDialog(null, "Tem Certeza que deseja votar nesse candidato?", "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
    if(confirma == JOptionPane.YES_OPTION){
    JOptionPane.showMessageDialog(null, "Você votou nesse candidato!");    
    }//GEN-LAST:event_btnconfirmaMouseClicked
    }}
    private void btnbrancoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbrancoMouseClicked
    corrige01();
    int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja votar em branco?", "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
    if(confirma == JOptionPane.YES_OPTION){
    JOptionPane.showMessageDialog(null, "Seu voto foi em branco!");    
    }
            }//GEN-LAST:event_btnbrancoMouseClicked

    private void btncorrigeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncorrigeMouseClicked
    corrige01();
    }//GEN-LAST:event_btncorrigeMouseClicked
    private void corrige01(){
        
    candidato.setText("");
    numCand = "";
    nome.setText("");
    cargo.setText("");
    espac1.setText("");
    espac2.setText("");
    espac3.setText("");
    }
    private void MostrarNum(){
    if (espac1.getText().equals("")) {
        espac1.setText(nmr);
    } 
    else{
    if(espac2.getText().equals("")){
        espac2.setText(nmr);
    }
     else{
     if (espac3.getText().equals("")){
         espac3.setText(nmr);
                    
         numCand = espac1.getText() + espac2.getText() + espac3.getText();
         criaCandidato();
}}}}
    
    private void criaCandidato(){
    {
        
     try{
     ImageIcon image = new ImageIcon(this.getClass().getResource("/img/cand_" +numCand+ ".jpg"));
     Image img = image.getImage().getScaledInstance(candidato.getWidth(), candidato.getHeight(), Image.SCALE_SMOOTH);
     candidato.setIcon(new ImageIcon(img));           

     switch(numCand){
            
     case "110":
          nome.setText("Potter - PPA");
          cargo.setText("Presidente");
     break;
            
     case "111":
          nome.setText("Hermione - PTA");
          cargo.setText("Presidente");
     break;
                
     case "112":
          nome.setText("Rony - PSA");
          cargo.setText("Presidente");
     break;
     
     case "113":
          nome.setText("Draco - PPP");
          cargo.setText("Presidente");
     break;
 }}}}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Urna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Urna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbranco;
    private javax.swing.JButton btnconfirma;
    private javax.swing.JButton btncorrige;
    private javax.swing.JLabel candidato;
    private javax.swing.JLabel cargo;
    private javax.swing.JTextField espac1;
    private javax.swing.JTextField espac2;
    private javax.swing.JTextField espac3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton nmr0;
    private javax.swing.JButton nmr1;
    private javax.swing.JButton nmr2;
    private javax.swing.JButton nmr3;
    private javax.swing.JButton nmr4;
    private javax.swing.JButton nmr5;
    private javax.swing.JButton nmr6;
    private javax.swing.JButton nmr7;
    private javax.swing.JButton nmr8;
    private javax.swing.JButton nmr9;
    private javax.swing.JLabel nome;
    // End of variables declaration//GEN-END:variables
}
