

import classes.conexao;
import static classes.conexao.statement;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.lang.Thread.sleep;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aluno
 */
public class TelaSenha1 extends javax.swing.JFrame {
 Calendar now = Calendar.getInstance();
    Date datahora = new Date();
    
    String tipo = "";
    int senhaN = 0;
    int senhaP = 0;
    int id = 0;
        conexao comb = new conexao();
    /**
     * Creates new form TelaSenha1
     */
    public TelaSenha1() {
        initComponents();
       
    }
class dataHora implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent ae)
        {
               Calendar now = Calendar.getInstance();
               hora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        acesso = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        sus = new javax.swing.JLabel();
        saida1 = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dispens = new javax.swing.JLabel();
        lbsenha1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbsenha2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        acesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/acesso.jpg"))); // NOI18N
        acesso.setText("jLabel2");
        acesso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acesso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acessoMouseClicked(evt);
            }
        });
        getContentPane().add(acesso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, 109));

        data.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        data.setText("DATA");
        data.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        getContentPane().add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 335, -1, -1));

        sus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sus1.jpg"))); // NOI18N
        sus.setText("LOGO");
        getContentPane().add(sus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 153, 54));

        saida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/saida.png"))); // NOI18N
        saida1.setText("jLabel4");
        saida1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saida1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saida1MouseClicked(evt);
            }
        });
        getContentPane().add(saida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(427, 343, 50, 40));

        hora.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hora.setText("HORÁRIO");
        hora.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        getContentPane().add(hora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 362, -1, -1));

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 80, 110));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("RETIRE SUA SENHA");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        dispens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/dispensaa.png"))); // NOI18N
        dispens.setText("jLabel3");
        dispens.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dispens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dispensMouseClicked(evt);
            }
        });
        getContentPane().add(dispens, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 130, 110));

        lbsenha1.setBackground(new java.awt.Color(255, 255, 204));
        lbsenha1.setOpaque(true);
        lbsenha1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(lbsenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 80, 160));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        lbsenha2.setBackground(new java.awt.Color(153, 255, 153));
        lbsenha2.setOpaque(true);
        lbsenha2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(lbsenha2);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 410));

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 140, 70, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     ImageIcon image = new ImageIcon(this.getClass().getResource("/imagens/acesso.jpg"));
     Image img = image.getImage().getScaledInstance(acesso.getWidth(), acesso.getHeight(), Image.SCALE_SMOOTH);
     acesso.setIcon(new ImageIcon(img)); 
     
    SimpleDateFormat dt = new SimpleDateFormat("dd/MM/yyyy");
        data.setText(dt.format(datahora));
	
	Timer timer = new Timer(1000, new dataHora());
        timer.start();
        
        ImageIcon imagee = new ImageIcon(this.getClass().getResource("/imagens/saida.png"));
     Image imgg = imagee.getImage().getScaledInstance(saida1.getWidth(), saida1.getHeight(), Image.SCALE_DEFAULT);
     saida1.setIcon(new ImageIcon(imgg));
     
    lbsenha1.setVisible (false);
     
     ImageIcon imageeee = new ImageIcon(this.getClass().getResource("/imagens/sus1.jpg"));
     Image imgggg = imageeee.getImage().getScaledInstance(sus.getWidth(), sus.getHeight(), Image.SCALE_SMOOTH);
     sus.setIcon(new ImageIcon(imgggg));
     
     ImageIcon imageeeee = new ImageIcon(this.getClass().getResource("/imagens/dispensaa.png"));
     Image imggggg = imageeeee.getImage().getScaledInstance(dispens.getWidth(), dispens.getHeight(), Image.SCALE_SMOOTH);
     dispens.setIcon(new ImageIcon(imggggg));
     }//GEN-LAST:event_formWindowOpened

    private void saida1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saida1MouseClicked
    int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
    if(confirma == JOptionPane.YES_OPTION){
    System.exit(0);       }//GEN-LAST:event_saida1MouseClicked
    }
    private void acessoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acessoMouseClicked
tipo = "P";
senhaP ++;
pegaSenha(tipo);

geraSenha();
gravaBanco ();
    }//GEN-LAST:event_acessoMouseClicked

    private void dispensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dispensMouseClicked
tipo = "N";
pegaSenha(tipo);
//senhaN ++;
gravaBanco ();
geraSenha();    }//GEN-LAST:event_dispensMouseClicked
    
    private void geraSenha(){
        
       lbsenha1.setText("<html><br><h1 style='font-size:10px;text-align:right'>SENHA</p><br><br><p style='font-size:18px; text-align:right'>"+tipo+""+id+"</p><br><br><p style='font-size:8px;  text-align:right'>"+data.getText()+"</p><p  style='font-size:8px; text-align:right'>"+hora.getText()+"</p></html>");
       movimento();
    }
  
public void movimento()
    {
        new Thread()
        {
            public void run()
            { 

               int y = 380;
               int x = 0;
               
                while(true)
                {
                    if( x < 110 )
                    {
                        x = x+1; 
                        lbsenha1.setVisible (true);
                    lbsenha1.setLocation(y , x);  
                    }
                    try
                    {
                        sleep(6);
                    }
                    catch (Exception e)
                    {
                    }
                }
            }
            
        }.start();
    }

          String dbData ;  
          String dbHora;

 private void gravaBanco()
    {
        dbHora = String.format("%1$tH:%1$tM:%1$tS", now);
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        dbData = dt.format(datahora);
        String atendido = " ";
        
        String sql = "insert into tb01_sus values (";
               sql+= id + ",'" +tipo + "', 0, '" + dbData + "','" + dbHora + "')";
        try{

        comb.conectar();
        
       int qtdreg = conexao.runSQL(sql);

        comb.desconectar();
        
        }
        catch (Exception e){
             System.out.println(e.getMessage());
        }
    }

  private void pegaSenha(String tipo)
    {
        String sql = "Select max(tb01_id) from tb01_sus ";
               sql += " where tb01_tipo = '" + tipo + "'";
        try{

        id = 1;
                        
        comb.conectar();

        ResultSet rs = statement.executeQuery(sql);  
         
       
        if (rs.next()) 
        {
             id = rs.getInt(1);
        }
        
        id = id + 1; 
        
        comb.desconectar();
        }
        catch (Exception e){
             System.out.println(e.getMessage());
         }
    }
      
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSenha1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSenha1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSenha1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSenha1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
     public void run() {
                new TelaSenha1().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acesso;
    private javax.swing.JLabel data;
    private javax.swing.JLabel dispens;
    private javax.swing.JLabel hora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lbsenha1;
    private javax.swing.JLabel lbsenha2;
    private javax.swing.JLabel saida1;
    private javax.swing.JLabel sus;
    // End of variables declaration//GEN-END:variables

       
    }
