/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Marciano;

import java.awt.Color;
import java.awt.Image;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author miuke
 */
public class NewJFrame extends javax.swing.JFrame {
JLabel casa[] = new JLabel[10];
     
     int cont = 0, mabel = 0;
     boolean teste = false;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }
private void sorteio(){
        
    cont=0;
    teste = false;
    Random r = new Random();
    mabel = r.nextInt(9)+1;
    teste=false;
    vetorcas();
    
    System.out.print(mabel);
    }
private void casas()    
    {
    casa[0] = cas1;
    casa[1] = cas2;
    casa[2] = cas3;
    casa[3] = cas4;
    casa[4] = cas5;
    casa[5] = cas6;
    casa[6] = cas7;
    casa[7] = cas8;
    casa[8] = cas9;
    casa[9] = cas10;
    }
private void vetorcas() {
            
    for (int x = 0; x < 10; x++)
    
    {
    ImageIcon imagens = new ImageIcon(this.getClass().getResource("/imagens/casa1.png"));
    Image imag = imagens.getImage(). getScaledInstance(casa[x].getWidth(), casa[x]. getHeight(), Image.SCALE_DEFAULT);
    casa[x].setIcon(new ImageIcon(imag));
    }
    }
public void tiro(int bala){
       
   if (bala == mabel){
   msg.setText(null);
   JOptionPane.showMessageDialog(null, "Você achou a Mabel!"); 
   
   msg.setText("Clique em Start para jogar novamente!");
   teste=true;
   }
   if (bala > mabel){
   JOptionPane.showMessageDialog(null, "Errou.");
   msg.setText("Tente novamente");
   }
   if (bala < mabel){
   JOptionPane.showMessageDialog(null, "Errou.");
   msg.setText("Tente novamente");
   }
   if (cont >= 4){
   msg.setText(null);
   JOptionPane.showMessageDialog(null, "Chances Acabadas!");
   msg.setText("Clique em Start para jogar novamente!");
   System.exit(0);
   }
   
   cont++;
   
   if(teste){
   ImageIcon imagens = new ImageIcon(this.getClass().getResource("/imagens/mabel2.png"));
    Image imag = imagens.getImage(). getScaledInstance(casa[bala -1].getWidth(), casa[bala -1]. getHeight(), Image.SCALE_DEFAULT);
    casa[bala -1].setIcon(new ImageIcon(imag));
  

}
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        cas1 = new javax.swing.JLabel();
        cas2 = new javax.swing.JLabel();
        cas3 = new javax.swing.JLabel();
        cas4 = new javax.swing.JLabel();
        cas5 = new javax.swing.JLabel();
        cas6 = new javax.swing.JLabel();
        cas7 = new javax.swing.JLabel();
        cas8 = new javax.swing.JLabel();
        cas9 = new javax.swing.JLabel();
        cas10 = new javax.swing.JLabel();
        botao = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        cas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/casa1.png"))); // NOI18N
        cas1.setLabelFor(cas1);
        cas1.setText("jLabel1");
        cas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cas1MouseClicked(evt);
            }
        });

        cas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/casa1.png"))); // NOI18N
        cas2.setText("jLabel1");
        cas2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cas2MouseClicked(evt);
            }
        });

        cas3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/casa1.png"))); // NOI18N
        cas3.setText("jLabel1");
        cas3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cas3MouseClicked(evt);
            }
        });

        cas4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/casa1.png"))); // NOI18N
        cas4.setText("jLabel1");
        cas4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cas4MouseClicked(evt);
            }
        });

        cas5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/casa1.png"))); // NOI18N
        cas5.setText("jLabel1");
        cas5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cas5MouseClicked(evt);
            }
        });

        cas6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/casa1.png"))); // NOI18N
        cas6.setText("jLabel1");
        cas6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cas6MouseClicked(evt);
            }
        });

        cas7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/casa1.png"))); // NOI18N
        cas7.setText("jLabel1");
        cas7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cas7MouseClicked(evt);
            }
        });

        cas8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/casa1.png"))); // NOI18N
        cas8.setText("jLabel1");
        cas8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cas8MouseClicked(evt);
            }
        });

        cas9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/casa1.png"))); // NOI18N
        cas9.setText("jLabel1");
        cas9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cas9MouseClicked(evt);
            }
        });

        cas10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/casa1.png"))); // NOI18N
        cas10.setText("jLabel1");
        cas10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cas10MouseClicked(evt);
            }
        });

        botao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENS/start1.png"))); // NOI18N
        botao.setText("jLabel2");
        botao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoMouseClicked(evt);
            }
        });

        msg.setText("Clique em Start para começar!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cas1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cas6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cas2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cas7, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cas3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cas8, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(cas4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cas5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(cas9, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cas10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msg)
                            .addComponent(botao, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cas1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cas3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(cas4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cas5, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(cas2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cas9, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cas10, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cas6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cas7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cas8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addComponent(botao, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(msg)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        botao.getAccessibleContext().setAccessibleParent(botao);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
      ImageIcon imagem = new ImageIcon(this.getClass().getResource("/imagens/start1.png"));
     Image imag = imagem.getImage(). getScaledInstance(botao.getWidth(),botao.getHeight(), Image.SCALE_DEFAULT);
     botao.setIcon(new ImageIcon(imag));
     
    setSize(584, 570);
    this.getContentPane().setBackground( Color.WHITE);
    
    casas();
    vetorcas();
    msg.setText("Para começar, aperte no Start!");
    }//GEN-LAST:event_formWindowOpened

    private void botaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoMouseClicked
    msg.setText("Escolha sua casinha!");
      sorteio();
    }//GEN-LAST:event_botaoMouseClicked

    private void cas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cas1MouseClicked
    tiro(1);
    }//GEN-LAST:event_cas1MouseClicked

    private void cas2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cas2MouseClicked
    tiro(2);
    }//GEN-LAST:event_cas2MouseClicked

    private void cas3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cas3MouseClicked
       tiro(3); // TODO add your handling code here:
    }//GEN-LAST:event_cas3MouseClicked

    private void cas4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cas4MouseClicked
     tiro(4);   // TODO add your handling code here:
    }//GEN-LAST:event_cas4MouseClicked

    private void cas5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cas5MouseClicked
     tiro(5);   // TODO add your handling code here:
    }//GEN-LAST:event_cas5MouseClicked

    private void cas6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cas6MouseClicked
     tiro(6); // TODO add your handling code here:
    }//GEN-LAST:event_cas6MouseClicked

    private void cas7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cas7MouseClicked
      tiro(7);  // TODO add your handling code here:
    }//GEN-LAST:event_cas7MouseClicked

    private void cas8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cas8MouseClicked
       tiro(8); // TODO add your handling code here:
    }//GEN-LAST:event_cas8MouseClicked

    private void cas9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cas9MouseClicked
      tiro(9);  // TODO add your handling code here:
    }//GEN-LAST:event_cas9MouseClicked

    private void cas10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cas10MouseClicked
      tiro(10);  // TODO add your handling code here:
    }//GEN-LAST:event_cas10MouseClicked
                                                                                                                             
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel botao;
    private javax.swing.JLabel cas1;
    private javax.swing.JLabel cas10;
    private javax.swing.JLabel cas2;
    private javax.swing.JLabel cas3;
    private javax.swing.JLabel cas4;
    private javax.swing.JLabel cas5;
    private javax.swing.JLabel cas6;
    private javax.swing.JLabel cas7;
    private javax.swing.JLabel cas8;
    private javax.swing.JLabel cas9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel msg;
    // End of variables declaration//GEN-END:variables
}
